### PR TITLE
#84: Suggestions to improve credit card recipe

### PR DESCRIPTION
**Pull request by ybyzek**

### CODE REVIEW

**Comment by ybyzek** [comment]
@mjsax @rmoff trying to run through this recipe and it seems I can't get even the original recipe to run at the moment.

Questions:

1. `FD_TRANSACTIONS_ENRICHED` does not return anything (neither original recipe, nor PR).  Any idea why this might be the case?
2. For the same reason that repartitioning transactions was suggested to be removed, can repartitioning customers be removed as well?

```
CREATE STREAM FD_CUSTOMER_REKEYED WITH (KAFKA_TOPIC='FD_CUSTOMER_REKEYED') AS
  SELECT * 
   FROM FD_CUST_RAW_STREAM 
   PARTITION BY ID;
```

**Comment by mjsax** [comment]
> FD_TRANSACTIONS_ENRICHED does not return anything (neither original recipe, nor PR), and I've fiddled with it for a bit and maybe missing something very obvious, but any idea why this might be the case?

Sounds like a timestamp issue? We first `INSERT VALUEs` into `FD_TRANSACTIONS` streams, and next `INSERT VALUES` into `FD_CUST_RAW_STREAM`. Thus, the former have smaller timestamps and are processed first and thus join to an empty table?

Easy to verify by switching to `LEFT JOIN`.

The fix should be to insert the customer data before the transaction data: cf https://www.confluent.io/resources/kafka-summit-2020/the-flux-capacitor-of-kafka-streams-and-ksqldb/ and https://www.confluent.io/events/kafka-summit-europe-2021/temporal-joins-in-kafka-streams-and-ksqldb/

> For the same reason that repartitioning transactions was suggested to be removed, can repartitioning customers be removed as well?

No. The input topic does not have a key set, and thus we cannot create a TABLE using the input topic. Hence, we need the intermediate step to repartition expliclity to be able to define the TABLE on the repartitioned topic.

**Comment by ybyzek** [comment]
@mjsax thank you for the detailed explanation and suggested fix.  Latest commit addresses this issue, validated locally.  I'll run through it in CCloud one more time to confirm.

**Comment by ybyzek** [comment]
This recipe works in CCloud. ✅

**Pull request merged**
