### PR TITLE
Fixing dynamic-pricing imports.

### PR DESCRIPTION
**Pull request by jnh5y**
Fixes https://confluentinc.github.io/ksqldb-recipes/real-time-analytics/dynamic-pricing/#ksqldb-code.  That page currently does not import the sql and other code blocks.

### CODE REVIEW

**Comment by jnh5y** [comment]
@ybyzek thanks!  I think I have updated the PR!

**Review by ybyzek — APPROVED** [review]
@jnh5y enormous thank you for the PR, LGTM!

**Comment by jnh5y** [comment]
@ybyzek Happy to help.  Also, I do not have a write access to this repo, so someone else may need to merge this PR!

**Comment by ybyzek** [comment]
> @ybyzek Happy to help. Also, I do not have a write access to this repo, so someone else may need to merge this PR!

Done 🎉 thanks again!

**Pull request merged**
